export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}
